/**
 * Blocklist of known disposable/temporary email domains.
 * Used to prevent signups with throwaway addresses.
 */
const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  // Major temporary inbox services
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.de', 'guerrillamail.net',
  'guerrillamail.org', 'guerrillamailblock.com', 'grr.la', 'guerrillamail.info',
  'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'temp-mail.de',
  'throwaway.email', 'throwaway.com', 'throam.com',
  'yopmail.com', 'yopmail.fr', 'yopmail.net', 'yopmail.gq',
  'sharklasers.com', 'dispostable.com', 'maildrop.cc',
  'trashmail.com', 'trashmail.me', 'trashmail.net', 'trashmail.org',
  'fakeinbox.com', 'mohmal.com', 'mohmal.in', 'mohmal.tech',

  // 10-minute / temporary mail variants
  '10minutemail.com', '10minutemail.net', '10minutemail.org',
  '10minutemail.co.za', '10mail.org', '10mail.com',
  'minutemail.com', 'tempail.com', 'tempr.email',
  'tempmailo.com', 'tempmailer.com', 'tempmailer.de',

  // Popular abuse / spam domains
  'mailnesia.com', 'mailnator.com', 'malinater.com',
  'getnada.com', 'nada.email', 'nada.ltd',
  'getairmail.com', 'airmail.cc',
  'burnermail.io', 'burner.kiwi',
  'mailsac.com', 'inboxkitten.com',
  'harakirimail.com', 'discard.email',
  'discardmail.com', 'discardmail.de',
  'spamgourmet.com', 'spamgourmet.net',
  'mytemp.email', 'tempinbox.com', 'tempinbox.co.uk',
  'mailcatch.com', 'mailscrap.com',
  'mailexpire.com', 'mailmoat.com',
  'mailnull.com', 'mailshell.com',
  'mailzilla.com', 'mailzilla.org',

  // Guerrilla / disposable networks
  'spam4.me', 'spamfree24.org', 'spamhereplease.com',
  'bugmenot.com', 'binkmail.com',
  'bobmail.info', 'bofthew.com',
  'boun.cr', 'bouncr.com',

  // Disposable email services (misc)
  'crazymailing.com', 'deadaddress.com',
  'despam.it', 'devnullmail.com',
  'disposeamail.com', 'disposemail.com',
  'dodgeit.com', 'dodgit.com',
  'dontreg.com', 'dontsendmespam.de',
  'dump-email.info', 'dumpmail.de',
  'dumpyemail.com', 'e4ward.com',
  'emailigo.de', 'emailisvalid.com',
  'emailmiser.com', 'emailproxsy.com',
  'emailsensei.com', 'emailtemporario.com.br',
  'emailthe.net', 'emailtmp.com',
  'emailwarden.com', 'emailx.at.hm',
  'emailxfer.com', 'emz.net',
  'enterto.com', 'ephemail.net',

  // Fast / instant disposable
  'facenewsk.com', 'filzmail.com',
  'fixmail.tk', 'flyspam.com',
  'frapmail.com', 'front14.org',
  'fux0ringduh.com', 'garliclife.com',
  'get1mail.com', 'get2mail.fr',
  'getonemail.com', 'getonemail.net',
  'ghosttexter.de', 'girlsundertheinfluence.com',
  'gishpuppy.com', 'goemailgo.com',
  'gotmail.com', 'gotmail.net', 'gotmail.org',
  'great-host.in', 'greensloth.com',

  // H-L misc
  'haltospam.com', 'hotpop.com',
  'ieatspam.eu', 'ieatspam.info',
  'imails.info', 'inbax.tk',
  'inbox.si', 'incognitomail.com',
  'incognitomail.net', 'incognitomail.org',
  'insorg-mail.info', 'ipoo.org',
  'irish2me.com', 'jetable.com',
  'jetable.fr.nf', 'jetable.net',
  'jetable.org', 'jnxjn.com',
  'junk1e.com', 'kasmail.com',
  'kaspop.com', 'keepmymail.com',
  'killmail.com', 'killmail.net',
  'klzlk.com', 'koszmail.pl',
  'kurzepost.de', 'lawlita.com',
  'letthemeatspam.com', 'lhsdv.com',
  'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to',
  'lookugly.com', 'lopl.co.cc',
  'lortemail.dk', 'lovemeleaveme.com',

  // M-P misc
  'mailbidon.com', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz',
  'maileme101.com', 'mailexpire.com',
  'mailfa.tk', 'mailforspam.com',
  'mailfree.ga', 'mailfree.gq',
  'mailfree.ml', 'mailfreeonline.com',
  'mailfs.com', 'mailguard.me',
  'mailhazard.com', 'mailhazard.us',
  'mailhz.me', 'mailimate.com',
  'mailin8r.com', 'mailinater.com',
  'mailinator.net', 'mailinator.org',
  'mailinator2.com', 'mailincubator.com',
  'mailismagic.com', 'mailmate.com',
  'mailme.ir', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com',
  'mailquack.com', 'mailrock.biz',
  'mailseal.de', 'mailsiphon.com',
  'mailslite.com', 'mailtemp.info',
  'mailtothis.com', 'mailtrash.net',
  'mailzilla.com', 'makemetheking.com',
  'manifestgenerator.com', 'mezimages.net',
  'mfsa.ru', 'mintemail.com',
  'misterpinball.de', 'mmmmail.com',
  'moakt.com', 'mobi.web.id',
  'mobileninja.co.uk', 'moneypipe.net',
  'msa.minsmail.com', 'mt2015.com',
  'mx0.wwwnew.eu', 'my10minutemail.com',
  'mypartyclip.de', 'myphantom.com',
  'mysamp.de', 'myspaceinc.com',
  'myspaceinc.net', 'myspaceinc.org',
  'myspacepimpedup.com', 'mytrashmail.com',

  // N-R misc
  'neomailbox.com', 'nepwk.com',
  'nervmich.net', 'nervtansen.de',
  'netmails.com', 'netmails.net',
  'neverbox.com', 'no-spam.ws',
  'nobulk.com', 'noclickemail.com',
  'nogmailspam.info', 'nomail.xl.cx',
  'nomail2me.com', 'nomorespamemails.com',
  'nospam.ze.tc', 'nospam4.us',
  'nospamfor.us', 'nospammail.net',
  'nothingtoseehere.ca', 'nowmymail.com',
  'nurfuerspam.de', 'nus.edu.sg',
  'objectmail.com', 'obobbo.com',
  'odaymail.com', 'oneoffemail.com',
  'onewaymail.com', 'oopi.org',
  'ordinaryamerican.net', 'owlpic.com',
  'pancakemail.com', 'pimpedupmyspace.com',
  'pjjkp.com', 'plexolan.de',
  'pookmail.com', 'privacy.net',
  'proxymail.eu', 'prtnx.com',
  'punkass.com', 'putthisinyouremail.com',

  // Q-Z misc
  'qq.com',
  'quickinbox.com', 'rcpt.at',
  'reallymymail.com', 'recode.me',
  'recursor.net', 'regbypass.com',
  'rejectmail.com', 'rhyta.com',
  'rklips.com', 'rmqkr.net',
  'royal.net', 'rppkn.com',
  'rtrtr.com', 's0ny.net',
  'safe-mail.net', 'safersignup.de',
  'safetymail.info', 'safetypost.de',
  'sandelf.de', 'saynotospams.com',
  'scatmail.com', 'schafmail.de',
  'selfdestructingmail.com', 'sendspamhere.com',
  'shiftmail.com', 'shitmail.me',
  'shortmail.net', 'sibmail.com',
  'skeefmail.com', 'slaskpost.se',
  'slipry.net', 'slopsbox.com',
  'smashmail.de', 'snoopmail.com',
  'sofimail.com', 'sofort-mail.de',
  'softpls.asia', 'sogetthis.com',
  'soodonims.com', 'spam.la',
  'spamavert.com', 'spambob.com',
  'spambob.net', 'spambob.org',
  'spambog.com', 'spambog.de',
  'spambog.ru', 'spambox.us',
  'spamcannon.com', 'spamcannon.net',
  'spamcero.com', 'spamcon.org',
  'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org',
  'spamday.com', 'spamex.com',
  'spamfighter.cf', 'spamfighter.ga',
  'spamfighter.gq', 'spamfighter.ml',
  'spamfighter.tk', 'spamfree.eu',
  'spamfree24.com', 'spamfree24.de',
  'spamfree24.info', 'spamfree24.net',
  'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info',
  'spaml.com', 'spaml.de',
  'spammotel.com', 'spamobox.com',
  'spamoff.de', 'spamslicer.com',
  'spamspot.com', 'spamstack.net',
  'spamtrail.com', 'spamtrap.ro',
  'speed.1s.fr', 'superrito.com',
  'suremail.info', 'svk.jp',
  'sweetxxx.de', 'tafmail.com',
  'tagyoureit.com', 'talkinator.com',
  'tapchicuoihoi.com', 'teleworm.us',
  'thankyou2010.com', 'thc.st',
  'thetempmail.com', 'thisisnotmyrealemail.com',
  'thismail.net', 'throwam.com',
  'tmail.ws', 'tmailinator.com',
  'toiea.com', 'tradermail.info',
  'trash-amil.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de',
  'trash2009.com', 'trashemail.de',
  'trashmail.at', 'trashmail.io',
  'trashmailer.com', 'trashymail.com',
  'trashymail.net', 'trbvm.com',
  'trbvn.com', 'trialmail.de',
  'trickmail.net', 'trillianpro.com',
  'turual.com', 'twinmail.de',
  'tyldd.com', 'uggsrock.com',
  'upliftnow.com', 'uplipht.com',
  'venompen.com', 'veryreallyanonymous.com',
  'viditag.com', 'viewcastmedia.com',
  'viewcastmedia.net', 'viewcastmedia.org',
  'vomoto.com', 'vpn.st',
  'vsimcard.com', 'vubby.com',
  'wasteland.rfc822.org', 'webemail.me',
  'weetnode.info', 'wetrainbayarea.com',
  'wetrainbayarea.org', 'wh4f.org',
  'whatiaas.com', 'whatpaas.com',
  'whyspam.me', 'wikidocuslice.com',
  'willhackforfood.biz', 'willselfdestruct.com',
  'winemaven.info', 'wronghead.com',
  'wuzup.net', 'wuzupmail.net',
  'wwwnew.eu', 'xagloo.com',
  'xemaps.com', 'xents.com',
  'xjoi.com', 'xmaily.com',
  'xoxy.net', 'yapped.net',
  'yep.it', 'yogamaven.com',
  'yuurok.com', 'zehnminutenmail.de',
  'zippymail.info', 'zoaxe.com',
  'zoemail.org',
]);

/**
 * Check if an email address uses a known disposable/temporary email domain.
 * @param email - The email address to check
 * @returns true if the email domain is in the disposable blocklist
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1]?.toLowerCase();
  if (!domain) return false;
  return DISPOSABLE_EMAIL_DOMAINS.has(domain);
}
