// Centralized jurisdiction configuration for dynamic compliance fields
import { getCountryByCode } from './countries';

export interface JurisdictionConfig {
  name: string;
  currency: string;
  // Business tax labels
  taxIdLabel: string;
  taxIdPlaceholder: string;
  taxIdHint: string;
  showCac: boolean;
  cacLabel?: string;
  cacPlaceholder?: string;
  cacHint?: string;
  cacRequired?: boolean;
  showVat: boolean;
  vatLabel?: string;
  vatPlaceholder?: string;
  vatHint?: string;
  showStateTax?: boolean;
  stateTaxLabel?: string;
  stateTaxPlaceholder?: string;
  // Client-specific labels
  clientTaxIdLabel: string;
  clientTaxIdPlaceholder: string;
  clientTaxIdHint: string;
  showClientReg: boolean;
  clientRegLabel?: string;
  clientRegPlaceholder?: string;
  clientRegHint?: string;
  phonePrefix: string;
  // Address placeholders
  cityPlaceholder: string;
  statePlaceholder: string;
  stateLabel: string;
  postalCodePlaceholder: string;
  postalCodeLabel: string;
  countryName: string;
}

// Detailed configurations for Tier 1 markets (full compliance labels)
export const JURISDICTION_CONFIG: Record<string, JurisdictionConfig> = {
  // ============= AFRICA =============
  NG: {
    name: 'Nigeria',
    currency: 'NGN',
    taxIdLabel: 'Tax Identification Number (TIN)',
    taxIdPlaceholder: '12345678-0001',
    taxIdHint: 'Your FIRS-issued Tax Identification Number',
    showCac: true,
    cacLabel: 'CAC Registration Number',
    cacPlaceholder: 'RC 123456',
    cacHint: 'Corporate Affairs Commission registration number for registered companies',
    cacRequired: false,
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '12345678',
    vatHint: 'Your FIRS-issued VAT registration number',
    clientTaxIdLabel: 'Tax Identification Number (TIN)',
    clientTaxIdPlaceholder: '12345678-0001',
    clientTaxIdHint: 'Required for B2B invoices per FIRS regulations',
    showClientReg: true,
    clientRegLabel: 'CAC Registration Number',
    clientRegPlaceholder: 'RC 123456',
    clientRegHint: 'Corporate Affairs Commission registration number',
    phonePrefix: '+234',
    cityPlaceholder: 'Lagos',
    statePlaceholder: 'Lagos State',
    stateLabel: 'State',
    postalCodePlaceholder: '100001',
    postalCodeLabel: 'Postal Code',
    countryName: 'Nigeria',
  },
  GH: {
    name: 'Ghana',
    currency: 'GHS',
    taxIdLabel: 'Tax Identification Number (TIN)',
    taxIdPlaceholder: 'C0012345678',
    taxIdHint: 'Your GRA-issued Tax Identification Number',
    showCac: true,
    cacLabel: 'Company Registration Number',
    cacPlaceholder: 'CS123456789',
    cacHint: 'Registrar General Department company number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: 'V0012345678',
    vatHint: 'Your GRA-issued VAT registration number',
    clientTaxIdLabel: 'Tax Identification Number (TIN)',
    clientTaxIdPlaceholder: 'C0012345678',
    clientTaxIdHint: 'Required for VAT invoices per GRA regulations',
    showClientReg: true,
    clientRegLabel: 'Company Registration Number',
    clientRegPlaceholder: 'CS123456789',
    clientRegHint: 'Registrar General Department registration',
    phonePrefix: '+233',
    cityPlaceholder: 'Accra',
    statePlaceholder: 'Greater Accra',
    stateLabel: 'Region',
    postalCodePlaceholder: 'GA-123-4567',
    postalCodeLabel: 'Digital Address',
    countryName: 'Ghana',
  },
  KE: {
    name: 'Kenya',
    currency: 'KES',
    taxIdLabel: 'KRA PIN',
    taxIdPlaceholder: 'A012345678Z',
    taxIdHint: 'Your Kenya Revenue Authority PIN (11 characters)',
    showCac: true,
    cacLabel: 'Company Registration Number',
    cacPlaceholder: 'PVT-ABC1234',
    cacHint: 'Registrar of Companies certificate number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: 'A012345678Z',
    vatHint: 'Your KRA VAT registration (same as PIN if VAT registered)',
    clientTaxIdLabel: 'KRA PIN',
    clientTaxIdPlaceholder: 'A012345678Z',
    clientTaxIdHint: 'Required for B2B invoices per KRA regulations',
    showClientReg: true,
    clientRegLabel: 'Company Registration Number',
    clientRegPlaceholder: 'PVT-ABC1234',
    clientRegHint: 'Business registration certificate number',
    phonePrefix: '+254',
    cityPlaceholder: 'Nairobi',
    statePlaceholder: 'Nairobi County',
    stateLabel: 'County',
    postalCodePlaceholder: '00100',
    postalCodeLabel: 'Postal Code',
    countryName: 'Kenya',
  },
  ZA: {
    name: 'South Africa',
    currency: 'ZAR',
    taxIdLabel: 'Tax Reference Number',
    taxIdPlaceholder: '1234567890',
    taxIdHint: 'Your SARS-issued tax reference number (10 digits)',
    showCac: true,
    cacLabel: 'CIPC Registration Number',
    cacPlaceholder: '2020/123456/07',
    cacHint: 'Companies and Intellectual Property Commission number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '4123456789',
    vatHint: 'Your SARS VAT vendor number (10 digits starting with 4)',
    clientTaxIdLabel: 'Tax Reference Number',
    clientTaxIdPlaceholder: '1234567890',
    clientTaxIdHint: 'Required for VAT invoices per SARS regulations',
    showClientReg: true,
    clientRegLabel: 'CIPC Registration Number',
    clientRegPlaceholder: '2020/123456/07',
    clientRegHint: 'Company registration number',
    phonePrefix: '+27',
    cityPlaceholder: 'Johannesburg',
    statePlaceholder: 'Gauteng',
    stateLabel: 'Province',
    postalCodePlaceholder: '2000',
    postalCodeLabel: 'Postal Code',
    countryName: 'South Africa',
  },
  EG: {
    name: 'Egypt',
    currency: 'EGP',
    taxIdLabel: 'Tax Registration Number',
    taxIdPlaceholder: '123-456-789',
    taxIdHint: 'Your Egyptian Tax Authority registration number',
    showCac: true,
    cacLabel: 'Commercial Register Number',
    cacPlaceholder: '12345',
    cacHint: 'Commercial Register (السجل التجاري) number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '123456789',
    vatHint: 'Your ETA VAT registration number',
    clientTaxIdLabel: 'Tax Registration Number',
    clientTaxIdPlaceholder: '123-456-789',
    clientTaxIdHint: 'Required for B2B e-invoices per ETA regulations',
    showClientReg: true,
    clientRegLabel: 'Commercial Register Number',
    clientRegPlaceholder: '12345',
    clientRegHint: 'Commercial Register number',
    phonePrefix: '+20',
    cityPlaceholder: 'Cairo',
    statePlaceholder: 'Cairo Governorate',
    stateLabel: 'Governorate',
    postalCodePlaceholder: '11511',
    postalCodeLabel: 'Postal Code',
    countryName: 'Egypt',
  },
  RW: {
    name: 'Rwanda',
    currency: 'RWF',
    taxIdLabel: 'TIN',
    taxIdPlaceholder: '123456789',
    taxIdHint: 'Your Rwanda Revenue Authority TIN (9 digits)',
    showCac: true,
    cacLabel: 'Company Registration Number',
    cacPlaceholder: '123456789',
    cacHint: 'Rwanda Development Board registration number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '123456789',
    vatHint: 'Your RRA VAT registration number',
    clientTaxIdLabel: 'TIN',
    clientTaxIdPlaceholder: '123456789',
    clientTaxIdHint: 'Required for EBM invoices',
    showClientReg: false,
    phonePrefix: '+250',
    cityPlaceholder: 'Kigali',
    statePlaceholder: 'Kigali City',
    stateLabel: 'Province',
    postalCodePlaceholder: '',
    postalCodeLabel: 'Postal Code',
    countryName: 'Rwanda',
  },
  TZ: {
    name: 'Tanzania',
    currency: 'TZS',
    taxIdLabel: 'TIN',
    taxIdPlaceholder: '123-456-789',
    taxIdHint: 'Your Tanzania Revenue Authority TIN',
    showCac: true,
    cacLabel: 'BRELA Registration Number',
    cacPlaceholder: '12345678',
    cacHint: 'Business Registration and Licensing Agency number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '10-123456-A',
    vatHint: 'Your TRA VAT registration number',
    clientTaxIdLabel: 'TIN',
    clientTaxIdPlaceholder: '123-456-789',
    clientTaxIdHint: 'Required for EFD receipts',
    showClientReg: true,
    clientRegLabel: 'BRELA Number',
    clientRegPlaceholder: '12345678',
    clientRegHint: 'Business registration number',
    phonePrefix: '+255',
    cityPlaceholder: 'Dar es Salaam',
    statePlaceholder: 'Dar es Salaam',
    stateLabel: 'Region',
    postalCodePlaceholder: '',
    postalCodeLabel: 'Postal Code',
    countryName: 'Tanzania',
  },
  UG: {
    name: 'Uganda',
    currency: 'UGX',
    taxIdLabel: 'TIN',
    taxIdPlaceholder: '1001234567',
    taxIdHint: 'Your Uganda Revenue Authority TIN (10 digits)',
    showCac: true,
    cacLabel: 'Company Registration Number',
    cacPlaceholder: '80020001234567',
    cacHint: 'URSB company registration number',
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: '1001234567',
    vatHint: 'Your URA VAT registration number',
    clientTaxIdLabel: 'TIN',
    clientTaxIdPlaceholder: '1001234567',
    clientTaxIdHint: 'Required for EFRIS invoices',
    showClientReg: false,
    phonePrefix: '+256',
    cityPlaceholder: 'Kampala',
    statePlaceholder: 'Central Region',
    stateLabel: 'Region',
    postalCodePlaceholder: '',
    postalCodeLabel: 'Postal Code',
    countryName: 'Uganda',
  },
  SN: {
    name: 'Senegal',
    currency: 'XOF',
    taxIdLabel: 'NINEA',
    taxIdPlaceholder: '1234567 A B1',
    taxIdHint: 'Your NINEA (Numéro d\'Identification Nationale des Entreprises et Associations)',
    showCac: true,
    cacLabel: 'RCCM Number',
    cacPlaceholder: 'SN-DKR-2020-A-12345',
    cacHint: 'Registre du Commerce et du Crédit Mobilier number',
    showVat: false,
    clientTaxIdLabel: 'NINEA',
    clientTaxIdPlaceholder: '1234567 A B1',
    clientTaxIdHint: 'Required for B2B invoices',
    showClientReg: true,
    clientRegLabel: 'RCCM Number',
    clientRegPlaceholder: 'SN-DKR-2020-A-12345',
    clientRegHint: 'Commercial register number',
    phonePrefix: '+221',
    cityPlaceholder: 'Dakar',
    statePlaceholder: 'Dakar',
    stateLabel: 'Region',
    postalCodePlaceholder: '',
    postalCodeLabel: 'Code Postal',
    countryName: 'Senegal',
  },

  // ============= AMERICAS =============
  US: {
    name: 'United States',
    currency: 'USD',
    taxIdLabel: 'Employer Identification Number (EIN)',
    taxIdPlaceholder: '12-3456789',
    taxIdHint: 'Your IRS-issued EIN or SSN for sole proprietors',
    showCac: false,
    showVat: false,
    showStateTax: true,
    stateTaxLabel: 'State Tax ID',
    stateTaxPlaceholder: 'State-specific format',
    clientTaxIdLabel: 'Tax ID (EIN/SSN)',
    clientTaxIdPlaceholder: '12-3456789',
    clientTaxIdHint: 'Employer ID or Social Security Number for 1099 reporting',
    showClientReg: false,
    phonePrefix: '+1',
    cityPlaceholder: 'New York',
    statePlaceholder: 'NY',
    stateLabel: 'State',
    postalCodePlaceholder: '10001',
    postalCodeLabel: 'ZIP Code',
    countryName: 'United States',
  },
  CA: {
    name: 'Canada',
    currency: 'CAD',
    taxIdLabel: 'Business Number (BN)',
    taxIdPlaceholder: '123456789RC0001',
    taxIdHint: 'Your 15-character CRA Business Number',
    showCac: false,
    showVat: true,
    vatLabel: 'GST/HST Registration Number',
    vatPlaceholder: '123456789RT0001',
    vatHint: 'Your CRA GST/HST registration number',
    clientTaxIdLabel: 'Business Number (BN)',
    clientTaxIdPlaceholder: '123456789RC0001',
    clientTaxIdHint: 'For CRA reporting requirements',
    showClientReg: false,
    phonePrefix: '+1',
    cityPlaceholder: 'Toronto',
    statePlaceholder: 'Ontario',
    stateLabel: 'Province',
    postalCodePlaceholder: 'M5V 1A1',
    postalCodeLabel: 'Postal Code',
    countryName: 'Canada',
  },
  MX: {
    name: 'Mexico',
    currency: 'MXN',
    taxIdLabel: 'RFC',
    taxIdPlaceholder: 'XAXX010101000',
    taxIdHint: 'Your Registro Federal de Contribuyentes (13 characters)',
    showCac: false,
    showVat: true,
    vatLabel: 'RFC',
    vatPlaceholder: 'XAXX010101000',
    vatHint: 'Same as RFC - used for CFDI e-invoicing',
    clientTaxIdLabel: 'RFC',
    clientTaxIdPlaceholder: 'XAXX010101000',
    clientTaxIdHint: 'Required for CFDI e-invoices per SAT regulations',
    showClientReg: false,
    phonePrefix: '+52',
    cityPlaceholder: 'Ciudad de México',
    statePlaceholder: 'CDMX',
    stateLabel: 'Estado',
    postalCodePlaceholder: '06600',
    postalCodeLabel: 'Código Postal',
    countryName: 'Mexico',
  },
  BR: {
    name: 'Brazil',
    currency: 'BRL',
    taxIdLabel: 'CNPJ',
    taxIdPlaceholder: '12.345.678/0001-90',
    taxIdHint: 'Your Cadastro Nacional da Pessoa Jurídica (14 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'Inscrição Estadual',
    vatPlaceholder: '123.456.789.012',
    vatHint: 'Your state tax registration number',
    clientTaxIdLabel: 'CNPJ/CPF',
    clientTaxIdPlaceholder: '12.345.678/0001-90',
    clientTaxIdHint: 'Required for NF-e (Nota Fiscal Eletrônica)',
    showClientReg: false,
    phonePrefix: '+55',
    cityPlaceholder: 'São Paulo',
    statePlaceholder: 'SP',
    stateLabel: 'Estado',
    postalCodePlaceholder: '01310-100',
    postalCodeLabel: 'CEP',
    countryName: 'Brazil',
  },
  AR: {
    name: 'Argentina',
    currency: 'ARS',
    taxIdLabel: 'CUIT',
    taxIdPlaceholder: '20-12345678-9',
    taxIdHint: 'Your Clave Única de Identificación Tributaria (11 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'Inscripción IVA',
    vatPlaceholder: '20-12345678-9',
    vatHint: 'Your AFIP IVA registration',
    clientTaxIdLabel: 'CUIT',
    clientTaxIdPlaceholder: '20-12345678-9',
    clientTaxIdHint: 'Required for facturas electrónicas',
    showClientReg: false,
    phonePrefix: '+54',
    cityPlaceholder: 'Buenos Aires',
    statePlaceholder: 'CABA',
    stateLabel: 'Provincia',
    postalCodePlaceholder: 'C1001',
    postalCodeLabel: 'Código Postal',
    countryName: 'Argentina',
  },
  CL: {
    name: 'Chile',
    currency: 'CLP',
    taxIdLabel: 'RUT',
    taxIdPlaceholder: '12.345.678-9',
    taxIdHint: 'Your Rol Único Tributario',
    showCac: false,
    showVat: true,
    vatLabel: 'RUT',
    vatPlaceholder: '12.345.678-9',
    vatHint: 'Same as RUT - for DTE e-invoicing',
    clientTaxIdLabel: 'RUT',
    clientTaxIdPlaceholder: '12.345.678-9',
    clientTaxIdHint: 'Required for DTE (Documento Tributario Electrónico)',
    showClientReg: false,
    phonePrefix: '+56',
    cityPlaceholder: 'Santiago',
    statePlaceholder: 'Región Metropolitana',
    stateLabel: 'Región',
    postalCodePlaceholder: '8320000',
    postalCodeLabel: 'Código Postal',
    countryName: 'Chile',
  },
  CO: {
    name: 'Colombia',
    currency: 'COP',
    taxIdLabel: 'NIT',
    taxIdPlaceholder: '900.123.456-7',
    taxIdHint: 'Your Número de Identificación Tributaria',
    showCac: false,
    showVat: true,
    vatLabel: 'NIT',
    vatPlaceholder: '900.123.456-7',
    vatHint: 'Same as NIT - for facturación electrónica',
    clientTaxIdLabel: 'NIT',
    clientTaxIdPlaceholder: '900.123.456-7',
    clientTaxIdHint: 'Required for factura electrónica per DIAN',
    showClientReg: false,
    phonePrefix: '+57',
    cityPlaceholder: 'Bogotá',
    statePlaceholder: 'Cundinamarca',
    stateLabel: 'Departamento',
    postalCodePlaceholder: '110111',
    postalCodeLabel: 'Código Postal',
    countryName: 'Colombia',
  },

  // ============= EUROPE =============
  GB: {
    name: 'United Kingdom',
    currency: 'GBP',
    taxIdLabel: 'Corporation Tax Reference (UTR)',
    taxIdPlaceholder: '1234567890',
    taxIdHint: 'Your HMRC Unique Taxpayer Reference (10 digits)',
    showCac: true,
    cacLabel: 'Companies House Number',
    cacPlaceholder: '12345678',
    cacHint: 'Your 8-character Companies House registration number',
    cacRequired: false,
    showVat: true,
    vatLabel: 'VAT Registration Number',
    vatPlaceholder: 'GB123456789',
    vatHint: 'Your HMRC-issued VAT number (GB + 9 or 12 digits)',
    clientTaxIdLabel: 'VAT Number / UTR',
    clientTaxIdPlaceholder: 'GB123456789',
    clientTaxIdHint: 'For HMRC compliance on B2B invoices',
    showClientReg: true,
    clientRegLabel: 'Companies House Number',
    clientRegPlaceholder: '12345678',
    clientRegHint: '8-character company registration number',
    phonePrefix: '+44',
    cityPlaceholder: 'London',
    statePlaceholder: 'Greater London',
    stateLabel: 'County',
    postalCodePlaceholder: 'SW1A 1AA',
    postalCodeLabel: 'Postcode',
    countryName: 'United Kingdom',
  },
  DE: {
    name: 'Germany',
    currency: 'EUR',
    taxIdLabel: 'Steuernummer (Tax Number)',
    taxIdPlaceholder: '123/456/78901',
    taxIdHint: 'Your German tax number from Finanzamt',
    showCac: true,
    cacLabel: 'Handelsregister Number',
    cacPlaceholder: 'HRB 12345',
    cacHint: 'Your commercial register (Handelsregister) entry',
    cacRequired: false,
    showVat: true,
    vatLabel: 'USt-IdNr (VAT ID)',
    vatPlaceholder: 'DE123456789',
    vatHint: 'Your EU VAT identification number',
    clientTaxIdLabel: 'Steuernummer',
    clientTaxIdPlaceholder: '123/456/78901',
    clientTaxIdHint: 'Tax number for German clients',
    showClientReg: true,
    clientRegLabel: 'Handelsregister Number',
    clientRegPlaceholder: 'HRB 12345',
    clientRegHint: 'Commercial register entry',
    phonePrefix: '+49',
    cityPlaceholder: 'Berlin',
    statePlaceholder: 'Berlin',
    stateLabel: 'Bundesland',
    postalCodePlaceholder: '10115',
    postalCodeLabel: 'PLZ',
    countryName: 'Germany',
  },
  FR: {
    name: 'France',
    currency: 'EUR',
    taxIdLabel: 'SIREN Number',
    taxIdPlaceholder: '123456789',
    taxIdHint: 'Your 9-digit SIREN identification number',
    showCac: true,
    cacLabel: 'SIRET Number',
    cacPlaceholder: '12345678901234',
    cacHint: 'Your 14-digit SIRET number (SIREN + NIC)',
    cacRequired: false,
    showVat: true,
    vatLabel: 'TVA Number',
    vatPlaceholder: 'FR12345678901',
    vatHint: 'Your French intra-community VAT number',
    clientTaxIdLabel: 'SIREN/SIRET',
    clientTaxIdPlaceholder: '123456789',
    clientTaxIdHint: 'French business identifier',
    showClientReg: true,
    clientRegLabel: 'SIRET Number',
    clientRegPlaceholder: '12345678901234',
    clientRegHint: '14-digit establishment identifier',
    phonePrefix: '+33',
    cityPlaceholder: 'Paris',
    statePlaceholder: 'Île-de-France',
    stateLabel: 'Region',
    postalCodePlaceholder: '75001',
    postalCodeLabel: 'Code Postal',
    countryName: 'France',
  },
  NL: {
    name: 'Netherlands',
    currency: 'EUR',
    taxIdLabel: 'KVK Number',
    taxIdPlaceholder: '12345678',
    taxIdHint: 'Your Chamber of Commerce (KVK) number',
    showCac: false,
    showVat: true,
    vatLabel: 'BTW Number',
    vatPlaceholder: 'NL123456789B01',
    vatHint: 'Your Dutch VAT identification number',
    clientTaxIdLabel: 'KVK / BTW Number',
    clientTaxIdPlaceholder: 'NL123456789B01',
    clientTaxIdHint: 'For Dutch B2B invoicing',
    showClientReg: false,
    phonePrefix: '+31',
    cityPlaceholder: 'Amsterdam',
    statePlaceholder: 'Noord-Holland',
    stateLabel: 'Province',
    postalCodePlaceholder: '1012 AB',
    postalCodeLabel: 'Postcode',
    countryName: 'Netherlands',
  },
  ES: {
    name: 'Spain',
    currency: 'EUR',
    taxIdLabel: 'NIF/CIF',
    taxIdPlaceholder: 'B12345678',
    taxIdHint: 'Your Número de Identificación Fiscal',
    showCac: false,
    showVat: true,
    vatLabel: 'NIF-IVA',
    vatPlaceholder: 'ESB12345678',
    vatHint: 'Your Spanish intra-community VAT number',
    clientTaxIdLabel: 'NIF/CIF',
    clientTaxIdPlaceholder: 'B12345678',
    clientTaxIdHint: 'Required for factura electrónica',
    showClientReg: false,
    phonePrefix: '+34',
    cityPlaceholder: 'Madrid',
    statePlaceholder: 'Comunidad de Madrid',
    stateLabel: 'Comunidad Autónoma',
    postalCodePlaceholder: '28001',
    postalCodeLabel: 'Código Postal',
    countryName: 'Spain',
  },
  IT: {
    name: 'Italy',
    currency: 'EUR',
    taxIdLabel: 'Codice Fiscale',
    taxIdPlaceholder: 'RSSMRA85M01H501Z',
    taxIdHint: 'Your Italian tax code (16 characters)',
    showCac: true,
    cacLabel: 'Partita IVA',
    cacPlaceholder: '12345678901',
    cacHint: 'Your 11-digit Italian VAT number',
    showVat: true,
    vatLabel: 'Partita IVA',
    vatPlaceholder: 'IT12345678901',
    vatHint: 'Your Italian intra-community VAT number',
    clientTaxIdLabel: 'Codice Fiscale / P.IVA',
    clientTaxIdPlaceholder: '12345678901',
    clientTaxIdHint: 'Required for fattura elettronica (FE)',
    showClientReg: false,
    phonePrefix: '+39',
    cityPlaceholder: 'Roma',
    statePlaceholder: 'Lazio',
    stateLabel: 'Regione',
    postalCodePlaceholder: '00100',
    postalCodeLabel: 'CAP',
    countryName: 'Italy',
  },
  PL: {
    name: 'Poland',
    currency: 'PLN',
    taxIdLabel: 'NIP',
    taxIdPlaceholder: '1234567890',
    taxIdHint: 'Your Numer Identyfikacji Podatkowej (10 digits)',
    showCac: true,
    cacLabel: 'KRS Number',
    cacPlaceholder: '0000123456',
    cacHint: 'National Court Register number',
    showVat: true,
    vatLabel: 'NIP-UE',
    vatPlaceholder: 'PL1234567890',
    vatHint: 'Your Polish intra-community VAT number',
    clientTaxIdLabel: 'NIP',
    clientTaxIdPlaceholder: '1234567890',
    clientTaxIdHint: 'Required for Polish VAT invoices',
    showClientReg: true,
    clientRegLabel: 'KRS Number',
    clientRegPlaceholder: '0000123456',
    clientRegHint: 'National Court Register number',
    phonePrefix: '+48',
    cityPlaceholder: 'Warszawa',
    statePlaceholder: 'Mazowieckie',
    stateLabel: 'Województwo',
    postalCodePlaceholder: '00-001',
    postalCodeLabel: 'Kod Pocztowy',
    countryName: 'Poland',
  },
  SE: {
    name: 'Sweden',
    currency: 'SEK',
    taxIdLabel: 'Organisationsnummer',
    taxIdPlaceholder: '123456-7890',
    taxIdHint: 'Your Swedish organization number (10 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'Momsregistreringsnummer',
    vatPlaceholder: 'SE123456789001',
    vatHint: 'Your Swedish VAT registration number',
    clientTaxIdLabel: 'Organisationsnummer',
    clientTaxIdPlaceholder: '123456-7890',
    clientTaxIdHint: 'Required for Swedish B2B invoices',
    showClientReg: false,
    phonePrefix: '+46',
    cityPlaceholder: 'Stockholm',
    statePlaceholder: 'Stockholm County',
    stateLabel: 'Län',
    postalCodePlaceholder: '111 22',
    postalCodeLabel: 'Postnummer',
    countryName: 'Sweden',
  },
  IE: {
    name: 'Ireland',
    currency: 'EUR',
    taxIdLabel: 'Tax Reference Number',
    taxIdPlaceholder: '1234567A',
    taxIdHint: 'Your Revenue-issued tax reference (7 digits + letter)',
    showCac: true,
    cacLabel: 'CRO Number',
    cacPlaceholder: '123456',
    cacHint: 'Companies Registration Office number',
    showVat: true,
    vatLabel: 'VAT Number',
    vatPlaceholder: 'IE1234567A',
    vatHint: 'Your Irish VAT registration number',
    clientTaxIdLabel: 'Tax Reference / VAT',
    clientTaxIdPlaceholder: 'IE1234567A',
    clientTaxIdHint: 'For Revenue compliance',
    showClientReg: true,
    clientRegLabel: 'CRO Number',
    clientRegPlaceholder: '123456',
    clientRegHint: 'Companies Registration Office number',
    phonePrefix: '+353',
    cityPlaceholder: 'Dublin',
    statePlaceholder: 'County Dublin',
    stateLabel: 'County',
    postalCodePlaceholder: 'D01 A1B2',
    postalCodeLabel: 'Eircode',
    countryName: 'Ireland',
  },
  BE: {
    name: 'Belgium',
    currency: 'EUR',
    taxIdLabel: 'Enterprise Number',
    taxIdPlaceholder: '0123.456.789',
    taxIdHint: 'Your Belgian enterprise number (10 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'BTW/TVA Number',
    vatPlaceholder: 'BE0123456789',
    vatHint: 'Your Belgian VAT identification number',
    clientTaxIdLabel: 'Enterprise / VAT Number',
    clientTaxIdPlaceholder: 'BE0123456789',
    clientTaxIdHint: 'For Belgian B2B invoicing',
    showClientReg: false,
    phonePrefix: '+32',
    cityPlaceholder: 'Brussels',
    statePlaceholder: 'Brussels-Capital',
    stateLabel: 'Region',
    postalCodePlaceholder: '1000',
    postalCodeLabel: 'Postcode',
    countryName: 'Belgium',
  },
  CH: {
    name: 'Switzerland',
    currency: 'CHF',
    taxIdLabel: 'UID Number',
    taxIdPlaceholder: 'CHE-123.456.789',
    taxIdHint: 'Your Unternehmens-Identifikationsnummer',
    showCac: false,
    showVat: true,
    vatLabel: 'MWST Number',
    vatPlaceholder: 'CHE-123.456.789 MWST',
    vatHint: 'Your Swiss VAT (Mehrwertsteuer) number',
    clientTaxIdLabel: 'UID / MWST Number',
    clientTaxIdPlaceholder: 'CHE-123.456.789',
    clientTaxIdHint: 'For Swiss VAT compliance',
    showClientReg: false,
    phonePrefix: '+41',
    cityPlaceholder: 'Zürich',
    statePlaceholder: 'Zürich',
    stateLabel: 'Kanton',
    postalCodePlaceholder: '8001',
    postalCodeLabel: 'PLZ',
    countryName: 'Switzerland',
  },

  // ============= ASIA-PACIFIC =============
  AU: {
    name: 'Australia',
    currency: 'AUD',
    taxIdLabel: 'ABN',
    taxIdPlaceholder: '12 345 678 901',
    taxIdHint: 'Your Australian Business Number (11 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'GST Registration',
    vatPlaceholder: '12 345 678 901',
    vatHint: 'Your ABN if registered for GST',
    clientTaxIdLabel: 'ABN',
    clientTaxIdPlaceholder: '12 345 678 901',
    clientTaxIdHint: 'Required for GST-compliant tax invoices',
    showClientReg: false,
    phonePrefix: '+61',
    cityPlaceholder: 'Sydney',
    statePlaceholder: 'NSW',
    stateLabel: 'State/Territory',
    postalCodePlaceholder: '2000',
    postalCodeLabel: 'Postcode',
    countryName: 'Australia',
  },
  IN: {
    name: 'India',
    currency: 'INR',
    taxIdLabel: 'GSTIN',
    taxIdPlaceholder: '22AAAAA0000A1Z5',
    taxIdHint: 'Your 15-digit Goods and Services Tax ID',
    showCac: true,
    cacLabel: 'CIN',
    cacPlaceholder: 'U12345MH2020PTC123456',
    cacHint: 'Corporate Identity Number (21 characters)',
    showVat: true,
    vatLabel: 'GSTIN',
    vatPlaceholder: '22AAAAA0000A1Z5',
    vatHint: 'Same as GSTIN - for e-invoicing',
    clientTaxIdLabel: 'GSTIN / PAN',
    clientTaxIdPlaceholder: '22AAAAA0000A1Z5',
    clientTaxIdHint: 'Required for B2B e-invoices per GST regulations',
    showClientReg: true,
    clientRegLabel: 'CIN',
    clientRegPlaceholder: 'U12345MH2020PTC123456',
    clientRegHint: 'Corporate Identity Number',
    phonePrefix: '+91',
    cityPlaceholder: 'Mumbai',
    statePlaceholder: 'Maharashtra',
    stateLabel: 'State',
    postalCodePlaceholder: '400001',
    postalCodeLabel: 'PIN Code',
    countryName: 'India',
  },
  JP: {
    name: 'Japan',
    currency: 'JPY',
    taxIdLabel: 'Corporate Number',
    taxIdPlaceholder: '1234567890123',
    taxIdHint: 'Your 13-digit corporate number (法人番号)',
    showCac: false,
    showVat: true,
    vatLabel: 'Consumption Tax Number',
    vatPlaceholder: 'T1234567890123',
    vatHint: 'Your qualified invoice issuer registration number',
    clientTaxIdLabel: 'Corporate Number',
    clientTaxIdPlaceholder: '1234567890123',
    clientTaxIdHint: 'Required for qualified invoices (適格請求書)',
    showClientReg: false,
    phonePrefix: '+81',
    cityPlaceholder: 'Tokyo',
    statePlaceholder: 'Tokyo',
    stateLabel: 'Prefecture',
    postalCodePlaceholder: '100-0001',
    postalCodeLabel: '〒',
    countryName: 'Japan',
  },
  SG: {
    name: 'Singapore',
    currency: 'SGD',
    taxIdLabel: 'UEN',
    taxIdPlaceholder: '201912345A',
    taxIdHint: 'Your Unique Entity Number (9-10 characters)',
    showCac: false,
    showVat: true,
    vatLabel: 'GST Registration Number',
    vatPlaceholder: '201912345A',
    vatHint: 'Your IRAS GST registration number',
    clientTaxIdLabel: 'UEN',
    clientTaxIdPlaceholder: '201912345A',
    clientTaxIdHint: 'Required for GST-registered businesses',
    showClientReg: false,
    phonePrefix: '+65',
    cityPlaceholder: 'Singapore',
    statePlaceholder: '',
    stateLabel: 'District',
    postalCodePlaceholder: '018956',
    postalCodeLabel: 'Postal Code',
    countryName: 'Singapore',
  },
  HK: {
    name: 'Hong Kong',
    currency: 'HKD',
    taxIdLabel: 'Business Registration Number',
    taxIdPlaceholder: '12345678-000-00-00-0',
    taxIdHint: 'Your IRD Business Registration Certificate number',
    showCac: true,
    cacLabel: 'CR Number',
    cacPlaceholder: '1234567',
    cacHint: 'Companies Registry number',
    showVat: false,
    clientTaxIdLabel: 'BR Number',
    clientTaxIdPlaceholder: '12345678-000-00-00-0',
    clientTaxIdHint: 'Business Registration number',
    showClientReg: true,
    clientRegLabel: 'CR Number',
    clientRegPlaceholder: '1234567',
    clientRegHint: 'Companies Registry number',
    phonePrefix: '+852',
    cityPlaceholder: 'Hong Kong',
    statePlaceholder: 'Hong Kong Island',
    stateLabel: 'District',
    postalCodePlaceholder: '',
    postalCodeLabel: '',
    countryName: 'Hong Kong',
  },
  AE: {
    name: 'United Arab Emirates',
    currency: 'AED',
    taxIdLabel: 'TRN',
    taxIdPlaceholder: '100123456700003',
    taxIdHint: 'Your Tax Registration Number (15 digits)',
    showCac: true,
    cacLabel: 'Trade License Number',
    cacPlaceholder: '123456',
    cacHint: 'Your DED or free zone trade license number',
    showVat: true,
    vatLabel: 'TRN',
    vatPlaceholder: '100123456700003',
    vatHint: 'Your FTA Tax Registration Number',
    clientTaxIdLabel: 'TRN',
    clientTaxIdPlaceholder: '100123456700003',
    clientTaxIdHint: 'Required for VAT invoices per FTA regulations',
    showClientReg: true,
    clientRegLabel: 'Trade License Number',
    clientRegPlaceholder: '123456',
    clientRegHint: 'Trade license number',
    phonePrefix: '+971',
    cityPlaceholder: 'Dubai',
    statePlaceholder: 'Dubai',
    stateLabel: 'Emirate',
    postalCodePlaceholder: '12345',
    postalCodeLabel: 'P.O. Box',
    countryName: 'United Arab Emirates',
  },
  SA: {
    name: 'Saudi Arabia',
    currency: 'SAR',
    taxIdLabel: 'VAT Registration Number',
    taxIdPlaceholder: '300000000000003',
    taxIdHint: 'Your ZATCA VAT registration number (15 digits)',
    showCac: true,
    cacLabel: 'CR Number',
    cacPlaceholder: '1010123456',
    cacHint: 'Commercial Registration number',
    showVat: true,
    vatLabel: 'VAT Number',
    vatPlaceholder: '300000000000003',
    vatHint: 'Your ZATCA VAT number',
    clientTaxIdLabel: 'VAT Number',
    clientTaxIdPlaceholder: '300000000000003',
    clientTaxIdHint: 'Required for e-invoicing (FATOORAH)',
    showClientReg: true,
    clientRegLabel: 'CR Number',
    clientRegPlaceholder: '1010123456',
    clientRegHint: 'Commercial Registration number',
    phonePrefix: '+966',
    cityPlaceholder: 'Riyadh',
    statePlaceholder: 'Riyadh Province',
    stateLabel: 'Province',
    postalCodePlaceholder: '12345',
    postalCodeLabel: 'Postal Code',
    countryName: 'Saudi Arabia',
  },
  MY: {
    name: 'Malaysia',
    currency: 'MYR',
    taxIdLabel: 'SST Registration Number',
    taxIdPlaceholder: 'A12-3456-78901234',
    taxIdHint: 'Your RMCD Sales and Service Tax registration',
    showCac: true,
    cacLabel: 'Company Registration Number',
    cacPlaceholder: '201901012345 (1234567-A)',
    cacHint: 'SSM company registration number',
    showVat: true,
    vatLabel: 'SST Number',
    vatPlaceholder: 'A12-3456-78901234',
    vatHint: 'Your SST registration number',
    clientTaxIdLabel: 'SST / Company Number',
    clientTaxIdPlaceholder: 'A12-3456-78901234',
    clientTaxIdHint: 'For e-Invoice compliance',
    showClientReg: true,
    clientRegLabel: 'Company Number',
    clientRegPlaceholder: '201901012345',
    clientRegHint: 'SSM registration number',
    phonePrefix: '+60',
    cityPlaceholder: 'Kuala Lumpur',
    statePlaceholder: 'Wilayah Persekutuan',
    stateLabel: 'State',
    postalCodePlaceholder: '50000',
    postalCodeLabel: 'Postcode',
    countryName: 'Malaysia',
  },
  ID: {
    name: 'Indonesia',
    currency: 'IDR',
    taxIdLabel: 'NPWP',
    taxIdPlaceholder: '12.345.678.9-012.000',
    taxIdHint: 'Your Nomor Pokok Wajib Pajak (15 digits)',
    showCac: true,
    cacLabel: 'NIB',
    cacPlaceholder: '1234567890123',
    cacHint: 'Nomor Induk Berusaha (13 digits)',
    showVat: true,
    vatLabel: 'PKP Number',
    vatPlaceholder: 'S-12345/PKP/WPJ.01/2020',
    vatHint: 'Your taxable entrepreneur certificate number',
    clientTaxIdLabel: 'NPWP',
    clientTaxIdPlaceholder: '12.345.678.9-012.000',
    clientTaxIdHint: 'Required for Faktur Pajak',
    showClientReg: true,
    clientRegLabel: 'NIB',
    clientRegPlaceholder: '1234567890123',
    clientRegHint: 'Business identification number',
    phonePrefix: '+62',
    cityPlaceholder: 'Jakarta',
    statePlaceholder: 'DKI Jakarta',
    stateLabel: 'Province',
    postalCodePlaceholder: '10110',
    postalCodeLabel: 'Kode Pos',
    countryName: 'Indonesia',
  },
  PH: {
    name: 'Philippines',
    currency: 'PHP',
    taxIdLabel: 'TIN',
    taxIdPlaceholder: '123-456-789-000',
    taxIdHint: 'Your BIR Tax Identification Number',
    showCac: true,
    cacLabel: 'SEC Registration Number',
    cacPlaceholder: 'CS201912345',
    cacHint: 'Securities and Exchange Commission registration',
    showVat: true,
    vatLabel: 'VAT TIN',
    vatPlaceholder: '123-456-789-00000',
    vatHint: 'Your BIR VAT registration',
    clientTaxIdLabel: 'TIN',
    clientTaxIdPlaceholder: '123-456-789-000',
    clientTaxIdHint: 'Required for official receipts',
    showClientReg: true,
    clientRegLabel: 'SEC Number',
    clientRegPlaceholder: 'CS201912345',
    clientRegHint: 'SEC registration number',
    phonePrefix: '+63',
    cityPlaceholder: 'Manila',
    statePlaceholder: 'Metro Manila',
    stateLabel: 'Region',
    postalCodePlaceholder: '1000',
    postalCodeLabel: 'ZIP Code',
    countryName: 'Philippines',
  },
  NZ: {
    name: 'New Zealand',
    currency: 'NZD',
    taxIdLabel: 'NZBN',
    taxIdPlaceholder: '9429041234567',
    taxIdHint: 'Your New Zealand Business Number (13 digits)',
    showCac: false,
    showVat: true,
    vatLabel: 'GST Number',
    vatPlaceholder: '123-456-789',
    vatHint: 'Your IRD GST registration number',
    clientTaxIdLabel: 'NZBN / GST Number',
    clientTaxIdPlaceholder: '123-456-789',
    clientTaxIdHint: 'For GST-compliant tax invoices',
    showClientReg: false,
    phonePrefix: '+64',
    cityPlaceholder: 'Auckland',
    statePlaceholder: 'Auckland',
    stateLabel: 'Region',
    postalCodePlaceholder: '1010',
    postalCodeLabel: 'Postcode',
    countryName: 'New Zealand',
  },
};

// Default config for unknown jurisdictions
export const DEFAULT_JURISDICTION_CONFIG: JurisdictionConfig = {
  name: 'International',
  currency: 'USD',
  taxIdLabel: 'Tax ID',
  taxIdPlaceholder: 'Enter your tax ID',
  taxIdHint: 'Your tax identification number',
  showCac: false,
  showVat: false,
  clientTaxIdLabel: 'Tax ID',
  clientTaxIdPlaceholder: 'Enter tax ID',
  clientTaxIdHint: 'Tax identification number for compliance',
  showClientReg: false,
  phonePrefix: '+1',
  cityPlaceholder: 'City',
  statePlaceholder: 'State/Region',
  stateLabel: 'State / Region',
  postalCodePlaceholder: 'Postal Code',
  postalCodeLabel: 'Postal Code',
  countryName: '',
};

/**
 * Get jurisdiction configuration for a country code.
 * Returns detailed config if available, otherwise builds a smart default from country data.
 */
export function getJurisdictionConfig(jurisdiction: string): JurisdictionConfig {
  // First check for specific detailed config
  if (JURISDICTION_CONFIG[jurisdiction]) {
    return JURISDICTION_CONFIG[jurisdiction];
  }
  
  // Build smart default from country data
  const country = getCountryByCode(jurisdiction);
  if (country) {
    return {
      ...DEFAULT_JURISDICTION_CONFIG,
      name: country.name,
      currency: country.currency,
      phonePrefix: country.phonePrefix,
      countryName: country.name,
      // Generic but country-aware hints
      taxIdHint: `Your ${country.name} tax identification number`,
      clientTaxIdHint: `Tax ID for ${country.name} compliance`,
    };
  }
  
  return DEFAULT_JURISDICTION_CONFIG;
}

// Helper to get CAC label based on jurisdiction (for display in invoices)
export function getCacDisplayLabel(jurisdiction: string): string {
  const config = getJurisdictionConfig(jurisdiction);
  if (!config.showCac) return 'Reg No';
  
  switch (jurisdiction) {
    case 'NG':
      return 'CAC';
    case 'GB':
      return 'Co. No';
    case 'DE':
      return 'HRB';
    case 'FR':
      return 'SIRET';
    case 'ZA':
      return 'CIPC';
    case 'IN':
      return 'CIN';
    case 'AE':
    case 'SA':
      return 'CR';
    default:
      return 'Reg No';
  }
}
