import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import { getCorsHeaders, checkRateLimit, rateLimitResponse } from '../_shared/validation.ts'
import { initSentry, captureException } from '../_shared/sentry.ts'
initSentry()

async function sendBrevoEmail(
  brevoApiKey: string,
  fromEmail: string,
  toEmail: string,
  subject: string,
  htmlContent: string,
): Promise<boolean> {
  const response = await fetch('https://api.brevo.com/v3/smtp/email', {
    method: 'POST',
    headers: {
      'accept': 'application/json',
      'api-key': brevoApiKey,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      sender: { name: 'InvoiceMonk', email: fromEmail },
      to: [{ email: toEmail }],
      subject,
      htmlContent,
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    console.error(`Brevo API error (${response.status}):`, errorText)
    return false
  }
  return true
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function buildEmailHtml(reportTitle: string, reportData: string, format: string, year: number): string {
  const formattedDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const dataBlock = format === 'json'
    ? `<pre style="background:#f4f4f5;padding:16px;border-radius:8px;overflow-x:auto;font-size:12px;line-height:1.5;max-height:600px;overflow-y:auto;white-space:pre-wrap;word-break:break-all;">${escapeHtml(reportData)}</pre>`
    : `<pre style="background:#f4f4f5;padding:16px;border-radius:8px;overflow-x:auto;font-size:12px;line-height:1.5;max-height:600px;overflow-y:auto;white-space:pre-wrap;">${escapeHtml(reportData)}</pre>`

  return `
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:32px 0;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden;">
        <tr><td style="background:#18181b;padding:24px 32px;">
          <h1 style="margin:0;color:#ffffff;font-size:20px;font-weight:700;">InvoiceMonk</h1>
        </td></tr>
        <tr><td style="padding:32px;">
          <h2 style="margin:0 0 8px;font-size:18px;color:#18181b;">${escapeHtml(reportTitle)}</h2>
          <p style="margin:0 0 24px;color:#71717a;font-size:14px;">Generated on ${formattedDate} for fiscal year ${year}</p>
          <p style="margin:0 0 12px;color:#3f3f46;font-size:14px;font-weight:600;">Report Data (${format.toUpperCase()}):</p>
          ${dataBlock}
          <hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;">
          <p style="margin:0;color:#a1a1aa;font-size:12px;">This report was generated by InvoiceMonk. For larger reports, use the download feature in-app.</p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`
}

Deno.serve(async (req) => {
  const corsHeaders = getCorsHeaders(req)

  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(JSON.stringify({ success: false, error: 'Authorization required' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseAnonKey = Deno.env.get('SUPABASE_ANON_KEY')!

    const supabaseUser = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: authHeader } },
    })

    const { data: { user }, error: authError } = await supabaseUser.auth.getUser()
    if (authError || !user) {
      return new Response(JSON.stringify({ success: false, error: 'Invalid or expired token' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Rate limit: 5 emails per hour
    const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const allowed = await checkRateLimit(serviceRoleKey, user.id, 'email-report', 3600, 5)
    if (!allowed) {
      return rateLimitResponse(corsHeaders)
    }

    const body = await req.json()
    const { report_title, report_data, recipient_email, format = 'csv', year } = body

    if (!report_title || typeof report_title !== 'string' || report_title.length > 200) {
      return new Response(JSON.stringify({ success: false, error: 'Valid report_title is required (max 200 chars)' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    if (!report_data || typeof report_data !== 'string') {
      return new Response(JSON.stringify({ success: false, error: 'report_data is required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    // Cap report data at 500KB to avoid email size issues
    if (report_data.length > 512000) {
      return new Response(JSON.stringify({ success: false, error: 'Report data too large for email. Please use the download feature instead.' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    const targetEmail = recipient_email || user.email
    if (!targetEmail || !emailRegex.test(targetEmail)) {
      return new Response(JSON.stringify({ success: false, error: 'Valid recipient email is required' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    if (!['csv', 'json'].includes(format)) {
      return new Response(JSON.stringify({ success: false, error: 'Format must be csv or json' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const reportYear = typeof year === 'number' ? year : new Date().getFullYear()

    const brevoApiKey = Deno.env.get('BREVO_API_KEY')
    const smtpFrom = Deno.env.get('SMTP_FROM') || 'noreply@invoicemonk.com'

    if (!brevoApiKey) {
      console.error('BREVO_API_KEY not configured')
      return new Response(
        JSON.stringify({ success: false, error: 'Email service not configured' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const subject = `${report_title} — ${reportYear} | InvoiceMonk`
    const html = buildEmailHtml(report_title, report_data, format, reportYear)

    const sent = await sendBrevoEmail(brevoApiKey, smtpFrom, targetEmail, subject, html)

    if (!sent) {
      return new Response(
        JSON.stringify({ success: false, error: 'Failed to send email' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    console.log(`Report email sent: ${report_title} to ${targetEmail}`)

    return new Response(
      JSON.stringify({ success: true, message: `Report sent to ${targetEmail}` }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  } catch (error) {
    console.error('email-report error:', error)
    captureException(error, { function_name: 'email-report' })
    return new Response(
      JSON.stringify({ success: false, error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
