GRANT EXECUTE ON FUNCTION public.get_business_sensitive(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_business_sensitive_fields(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dashboard_stats(uuid, uuid, timestamptz, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_due_date_stats(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_accounting_stats(uuid, uuid, timestamptz, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_cashflow_summary(uuid, uuid, timestamptz, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_expenses_by_category(uuid, uuid, timestamptz, timestamptz) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_profitability_stats(uuid, uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_receivables_intelligence(uuid, uuid, date, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_revenue_trend(uuid, uuid, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_tier(uuid, subscription_tier) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_tier_limit(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_tier_limit_business(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_currency_account_limit(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_payment_method_limit(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_receipt_limit() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_team_member_limit() TO authenticated;
GRANT EXECUTE ON FUNCTION public.issue_invoice(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.log_audit_event(audit_event_type, text, uuid, uuid, uuid, jsonb, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_notification(uuid, text, text, text, text, uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_regulatory_submission(uuid, uuid, uuid, text, text, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_submission_status(uuid, text, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.lock_business_currency() TO authenticated;
GRANT EXECUTE ON FUNCTION public.close_account(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_disposable_email() TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_rate_limit(text, text, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_business_documents(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_get_verification_queue(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_paid_intent_lost_count(integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_verification(uuid, text, text, text, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.ban_user(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unban_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_platform_admin_emails() TO authenticated;